# Install packages

First thing is to install pandas, numpy, scikit-learn, matplotlib, and seaborn. Then below you see where we import the packages in our notebook.

In [53]:
import pandas as pd
import numpy as np
import datetime as dt

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score




from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV

from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, ElasticNet, Lasso
from sklearn.metrics import classification_report, mean_squared_error, confusion_matrix, plot_confusion_matrix, accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, roc_curve, auc
from sklearn.preprocessing import StandardScaler

# allow multiple outputs per cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


# Import the data and start exploring it

In [4]:

data = pd.read_csv('../Project Retain Alabama/Survey Data and Info/UABformatChange.csv')
alabamaData = pd.read_csv('../Project Retain Alabama/Survey Data and Info/alabamaData.csv')
alabamaData.describe()

University     GradTime     Distance         Full         STEM  \
count  8208.000000  8208.000000  8208.000000  8208.000000  8208.000000   
mean      7.992446  2021.986111     0.316155     0.875975     0.306043   
std       3.226881     0.831072     0.465003     0.329631     0.460876   
min       1.000000  2021.000000     0.000000     0.000000     0.000000   
25%       6.000000  2021.000000     0.000000     1.000000     0.000000   
50%       8.000000  2022.000000     0.000000     1.000000     0.000000   
75%      10.000000  2023.000000     1.000000     1.000000     1.000000   
max      14.000000  2023.000000     1.000000     1.000000     1.000000   

       Alcareerlearn       StayAL  AL Resident  StateHScode         ALHS  ...  \
count    8208.000000  8208.000000  8208.000000  8208.000000  7855.000000  ...   
mean        0.725268     1.630361     0.642544     7.299464    36.898027  ...   
std         0.446406     1.250832     0.479280     2.649684    43.085221  ...   
min         0.000000     0.000000     0.000000     1.000000     1.000000  ...   
25%         0.000000     1.000000     0.000000     4.000000     5.000000  ...   
50%         1.000000     1.000000     1.000000     9.000000    10.000000  ...   
75%         1.000000     3.000000     1.000000     9.000000    99.000000  ...   
max         1.000000     3.000000     1.000000    10.000000    99.000000  ...   

       I_c_sporting  I_c_outdoor  AL Resident.1  StateHScode.1       ALHS.1  \
count   8208.000000  8208.000000         5274.0    8208.000000  7855.000000   
mean       3.467105     4.528996            1.0       7.299464    36.898027   
std        1.629699     0.997566            0.0       2.649684    43.085221   
min        1.000000     1.000000            1.0       1.000000     1.000000   
25%        3.000000     5.000000            1.0       4.000000     5.000000   
50%        3.000000     5.000000            1.0       9.000000    10.000000   
75%        5.000000     5.000000            1.0       9.000000    99.000000   
max        5.000000     5.000000            1.0      10.000000    99.000000   

          Gender.1  Race Code.1        Age.1  Disability.1   FirstGEn.1  
count  8208.000000  8208.000000  8208.000000   8171.000000  8185.000000  
mean      1.337110     3.498294     2.486964      0.051524     0.383262  
std       0.487471     1.025683     0.934468      0.221077     0.486211  
min       1.000000     1.000000     1.000000      0.000000     0.000000  
25%       1.000000     3.000000     2.000000      0.000000     0.000000  
50%       1.000000     4.000000     2.000000      0.000000     0.000000  
75%       2.000000     4.000000     3.000000      0.000000     1.000000  
max       3.000000     6.000000     7.000000      1.000000     1.000000  

[8 rows x 141 columns]

Some commands you could start with : 
- data.describe()
- data.shape
- data.isnull().sum()
- data['column name'].value_counts()

# Transform the Data for Regression

In [5]:
data = data.replace(np.NAN, 0)
alabamaData = alabamaData.replace(np.NAN, 0)
data = data.loc[:,~data.columns.duplicated()]
alabamaData = alabamaData.loc[:,~alabamaData.columns.duplicated()]

In [6]:
# Use get dummies for one hot encoding 
# pd.get_dummies(data.University, prefix='University Code')
readData = pd.get_dummies(data, columns=['Race','StateHS','Major','Major Code', 'Major Code Revised'])
readAlabamaData = pd.get_dummies(alabamaData, columns=['Race','StateHS','Major','Major Code', 'Major Code Revised'])

readData
readAlabamaData.describe()
# data = pd.concat([data, rd], axis=1)
# data
# print(data)

University  GradTime                          FTPT  Distance  Full  \
0              9      2021  Full-time Distance Education         1     1   
1              9      2021  Full-time Distance Education         1     1   
2              9      2022  Full-time Distance Education         1     1   
3              9      2022  Full-time Distance Education         1     1   
4              9      2022  Full-time Distance Education         1     1   
...          ...       ...                           ...       ...   ...   
1201           9      2022           Full-time On-Campus         0     1   
1202           9      2023           Full-time On-Campus         0     1   
1203           9      2023           Full-time On-Campus         0     1   
1204           9      2021  Part-time Distance Education         1     0   
1205           9      2023  Part-time Distance Education         1     0   

      STEM  Alcareerlearn  StayAL  AL Resident  StateHScode  ...  \
0        0              1       0            1            9  ...   
1        0              0       3            1            9  ...   
2        0              1       0            1            9  ...   
3        0              1       1            1            9  ...   
4        0              1       3            1            9  ...   
...    ...            ...     ...          ...          ...  ...   
1201     0              1       0            0            3  ...   
1202     0              0       1            0           10  ...   
1203     0              1       3            0           10  ...   
1204     1              0       3            0           10  ...   
1205     0              1       3            0            6  ...   

      Major Code_Other, Social Sciences  \
0                                     0   
1                                     0   
2                                     0   
3                                     0   
4                                     0   
...                                 ...   
1201                                  0   
1202                                  0   
1203                                  0   
1204                                  0   
1205                                  0   

      Major Code_Science, Technology, Engineering and Mathematics  \
0                                                     0             
1                                                     0             
2                                                     0             
3                                                     0             
4                                                     0             
...                                                 ...             
1201                                                  0             
1202                                                  0             
1203                                                  0             
1204                                                  0             
1205                                                  0             

      Major Code_Transportation, Distribution and Logistics  \
0                                                     0       
1                                                     0       
2                                                     0       
3                                                     0       
4                                                     0       
...                                                 ...       
1201                                                  0       
1202                                                  0       
1203                                                  0       
1204                                                  0       
1205                                                  0       

      Major Code Revised_Arts, A/V Technology and Communications  \
0                                                     1            
1                                    

University     GradTime     Distance         Full         STEM  \
count  8208.000000  8208.000000  8208.000000  8208.000000  8208.000000   
mean      7.992446  2021.986111     0.316155     0.875975     0.306043   
std       3.226881     0.831072     0.465003     0.329631     0.460876   
min       1.000000  2021.000000     0.000000     0.000000     0.000000   
25%       6.000000  2021.000000     0.000000     1.000000     0.000000   
50%       8.000000  2022.000000     0.000000     1.000000     0.000000   
75%      10.000000  2023.000000     1.000000     1.000000     1.000000   
max      14.000000  2023.000000     1.000000     1.000000     1.000000   

       Alcareerlearn       StayAL  AL Resident  StateHScode         ALHS  ...  \
count    8208.000000  8208.000000  8208.000000  8208.000000  8208.000000  ...   
mean        0.725268     1.630361     0.642544     7.299464    35.311160  ...   
std         0.446406     1.250832     0.479280     2.649684    42.808088  ...   
min         0.000000     0.000000     0.000000     1.000000     0.000000  ...   
25%         0.000000     1.000000     0.000000     4.000000     3.000000  ...   
50%         1.000000     1.000000     1.000000     9.000000    10.000000  ...   
75%         1.000000     3.000000     1.000000     9.000000    99.000000  ...   
max         1.000000     3.000000     1.000000    10.000000    99.000000  ...   

       Major Code_Other, Social Sciences  \
count                        8208.000000   
mean                            0.009259   
std                             0.095784   
min                             0.000000   
25%                             0.000000   
50%                             0.000000   
75%                             0.000000   
max                             1.000000   

       Major Code_Science, Technology, Engineering and Mathematics  \
count                                        8208.000000             
mean                                            0.224415             
std                                             0.417222             
min                                             0.000000             
25%                                             0.000000             
50%                                             0.000000             
75%                                             0.000000             
max                                             1.000000             

       Major Code_Transportation, Distribution and Logistics  \
count                                        8208.000000       
mean                                            0.009990       
std                                             0.099457       
min                                             0.000000       
25%                                             0.000000       
50%                                             0.000000       
75%                                             0.000000       
max                                             1.000000       

       Major Code Revised_Arts, A/V Technology and Communications  \
count                                        8208.000000            
mean                                            0.076633            
std                                             0.266024            
min                                             0.000000            
25%                                             0.000000            
50%                                             0.000000            
75%                                             0.000000            
max                                             1.000000            

       Major Code Revised_Business Management and Administration  \
count                                        8208.000000           
mean                                            0.187135           
std                                             0.390043           
min                                             0.000000           
25%                                         

In [7]:
readData['StayAL'].value_counts()
alabamaData['StayAL'].value_counts()

3    539
1    383
0    284
Name: StayAL, dtype: int64

3    3546
1    2744
0    1918
Name: StayAL, dtype: int64

In [ ]:
# A useful function for changing strings 
# for i in list(data.columns):
#     data[i] = data[i].apply(lambda x: str(x)).apply(lambda x: x.replace('|' , ','))
# data = data[~data.columns.duplicated()]
alabamaData.describe()

In [8]:
# renaming columns
pd.options.display.max_columns = 300
pd.options.display.max_rows = 10
# readData
readAlabamaData
# data = data.rename(columns = {'_Virginia': 'Virginia'})
# data
# Regressiona

University  GradTime                          FTPT  Distance  Full  \
0              1      2021  Full-time Distance Education         1     1   
1              1      2021  Full-time Distance Education         1     1   
2              1      2021  Full-time Distance Education         1     1   
3              1      2022  Full-time Distance Education         1     1   
4              1      2023  Full-time Distance Education         1     1   
...          ...       ...                           ...       ...   ...   
8203          14      2023  Part-time Distance Education         1     0   
8204          14      2023  Part-time Distance Education         1     0   
8205          14      2023  Part-time Distance Education         1     0   
8206          14      2023  Part-time Distance Education         1     0   
8207          14      2022           Part-time On-Campus         0     0   

      STEM  Alcareerlearn  StayAL  AL Resident  StateHScode  ALHS  Gender  \
0        1              1       0            1            9   3.0       1   
1        1              1       1            1            9  13.0       1   
2        1              1       1            1            9  15.0       1   
3        1              1       3            1            9   8.0       1   
4        1              1       3            1            9  10.0       1   
...    ...            ...     ...          ...          ...   ...     ...   
8203     0              0       0            0            3  99.0       2   
8204     0              1       3            0            3   4.0       1   
8205     0              0       3            0            3   0.0       1   
8206     0              1       1            0            3  99.0       1   
8207     0              1       3            0            3  99.0       1   

      Race Code  Age  Disability  FirstGEn  Rcurric  Rk-12  Rprof  Rfamily  \
0             2    2         0.0       1.0      1.0    0.0    0.0      0.0   
1             2    3         0.0       1.0      0.0    0.0    0.0      1.0   
2             2    2         0.0       1.0      1.0    0.0    0.0      0.0   
3             2    2         0.0       0.0      0.0    1.0    0.0      0.0   
4             2    2         0.0       0.0      1.0    0.0    1.0      1.0   
...         ...  ...         ...       ...      ...    ...    ...      ...   
8203          4    3         0.0       0.0      0.0    0.0    0.0      0.0   
8204          2    5         0.0       1.0      0.0    1.0    0.0      0.0   
8205          5    6         0.0       0.0      0.0    0.0    0.0      0.0   
8206          2    3         0.0       1.0      0.0    1.0    0.0      0.0   
8207          4    2         0.0       0.0      0.0    0.0    1.0      1.0   

      Rfriend  Rmedia  Rextra  Rindustry  Rhighscho  Rcollege  Rprospect  \
0         0.0     0.0     0.0        0.0        0.0       0.0        0.0   
1         0.0     0.0     0.0        0.0        0.0       0.0        0.0   
2         0.0     0.0     0.0        0.0        0.0       0.0        0.0   
3         0.0     1.0     1.0        0.0        0.0       0.0        0.0   
4         0.0     0.0     0.0        0.0        0.0       0.0        1.0   
...       ...     ...     ...        ...        ...       ...        ...   
8203      0.0     0.0     0.0        1.0        0.0       0.0        0.0   
8204      0.0     0.0     0.0        0.0        0.0       0.0        1.0   
8205      0.0     0.0     0.0        0.0        0.0       0.0        0.0   
8206      0.0     0.0     0.0        0.0        0.0       0.0        0.0   
8207      1.0     0.0     0.0        0.0        0.0       0.0        0.0   

      Rjob  Rother  ExploreAL  Eaubrun  Efoley  Ebham  Edemop  Edothan  Eflor  \
0      0.0     0.0          1      1.0     0.0    1.0     0.0      0.0    0.0   
1      0.0     0.0          1      1.0     1.0    1.0     0.0      0.0    0.0   
2      0.0     0.0          1      0.0     0.0    1.0     0.0      0.0    0

In [60]:
x = readAlabamaData['ALHS.1'].values.reshape(-1,1) 
print(x) #original is 8208 rows
print('mdddd')
y = readAlabamaData['StayAL'].values.reshape(-1,1)
print(y) #1206 rows 
# fix above this line. 
model = LogisticRegression(solver='liblinear', random_state=0).fit(x,y)
model.classes_
# print('Hoping for the best')
# model.predict_proba(y)
print('Hoping for the best x')
model.predict_proba(x)
print('The other bad boy')
model.predict(x)
# print('Holy moly')
# model.predict(y)
print('Lets get funky')

print('train')
# X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
# sc = StandardScaler()

# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(x, y)
plt.scatter(x,y)
plt.plot(y, regressor.predict(x),
         color = 'green')
# Y_pred = regressor.predict(X_train) # test the output by changing values




# confusion_matrix(y_test,y_pred)
# classification_report(y_test,y_pred)
# accuracy_score(y_test, y_pred)

# lin_reg = LinearRegression()
# lin_reg.fit(x, y)
# lin_reg.intercept_, lin_reg.coef_
# prayingToGod = lin_reg.predict(y)


# # 
# plt.scatter(x,y)
# plt.plot(x,prayingToGod,color='blue')
# plt.show()

[[ 3.]
 [13.]
 [15.]
 ...
 [ 0.]
 [99.]
 [99.]]
mdddd
[[0]
 [1]
 [1]
 ...
 [3]
 [1]
 [3]]


C:\Users\Gmike\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0, 1, 3], dtype=int64)

Hoping for the best x


array([[0.18188992, 0.41171354, 0.40639654],
       [0.19659169, 0.38628288, 0.41712543],
       [0.19961015, 0.38116786, 0.41922199],
       ...,
       [0.17761351, 0.41927553, 0.40311095],
       [0.33732905, 0.18270681, 0.47996414],
       [0.33732905, 0.18270681, 0.47996414]])

The other bad boy


array([1, 3, 3, ..., 1, 3, 3], dtype=int64)

Lets get funky
train


<ipython-input-60-65675013e781>:27: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(x, y)


RandomForestRegressor(n_estimators=20, random_state=0)

In [ ]:
# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)



# Model Validation

# 